version: '2'
services:
  jenkins:
    user: root
    restart: always
    image: 'bitnami/jenkins:2'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - './jenkins:/bitnami:rw'
      - '/home/maven3.6.3/:/home/maven3.6.3/:rw'
      - '/home/jenkins/:/home/jenkins/:rw'
   #   - './opt:/opt/:rw'
   #   - './jenkins_home:/opt/jenkins_docker/jenkins/jenkins/jenkins_home/:rw'
    environment:
      - 'JENKINS_USERNAME=admin'
      - 'JENKINS_PASSWORD=admin'
    network_mode: host
